# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Don't run pre-commit on files under third-party/
exclude: "^\
  (static/.*)\
  "
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-yaml # checks yaml files for parseable syntax.
        args: [ '--unsafe' ]
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.
      - id: check-json # if you have JSON files in your repo
      - id: file-contents-sorter #  if there are files that benefit from a reliable ordering, this is a handy hook
        # search for nameing conventions
      - id: name-tests-test

  # black
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.11
        args: ["--config=pyproject.toml"]

  - repo: local
    hooks:
      - id: no-print
        name: No print statements
        description: This hook checks if your Python code has any print statements.
        entry: no-print.sh
        language: script
        types: [python]
        files: \.py$-

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

#  - repo: https://github.com/pycqa/flake8
#    rev: 6.1.0 # pick a git hash / tag to point to
#    hooks:
#      - id: flake8
#        additional_dependencies: [flake8-docstrings, flake8-bugbear]
#        args: ["--config=setup.cfg"]

#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.5
#    hooks:
#      - id: bandit
#        name: bandit
#        description: "Bandit is a tool for finding common security issues in Python code"
#        entry: bandit
#        language: python
#        language_version: python311
#        types: [python]
